# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

# https://docs.travis-ci.com/user/database-setup/#PostgreSQL
before_script:
  - psql -c 'create database topjava' -U postgres
  - psql -c 'create user "postgres"; grant all privileges on database topjava to "postgres"' -U postgres
before_script:
  - psql -c 'create database topjava' -U postgres
  - psql -c 'create user "postgres";grant all privileges on database topjava to "postgres"' -U postgres